---
title: "M11_Inclass"
author: "Lionel Medal"
date: "2024-04-09"
output: pdf_document
---

## Excercise 11.1
```{r}
# install.packages("tidyverse")
library(tidyverse)
```


## Excercise 11.2

```{r}
scores <- 
  tibble(
    name = c("mike", "carol", "greg", "marcia", "peter", "jan", "bobby", "cindy", "alice"),
    school = c("south", "south", "south", "south", "north", "north", "north", "south", "south"),
    teacher = c("johnson", "johnson", "johnson", "johnson",  "smith", "smith", "smith", "perry", "perry"),
    sex = c("male", "female", "male", "female", "male", "female", "male", "female", "female"),
    math_score = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
    reading_score = c(1, 5, 2, 4, 5, 4, 1, 5, 4)
)
```


## Excercise 11.3

```{r}
scores
```


## Excercise 11.4

```{r}

scores %>% 
  slice(1:3)
```


## Excercise 11.5

```{r}

scores %>% 
  arrange(desc(math_score))
```

## Excercise 11.6

```{r}
scores %>% 
  arrange(name)
```

## Excercise 11.7

```{r}
scores %>% 
  arrange(sex)
```

## Excercise 11.8

```{r}
scores %>%
    arrange(school, teacher, sex, math_score, reading_score)
```

## Excercise 11.9

```{r}
scores %>% 
  select(name, math_score, reading_score)
```

## Excercise 11.10

```{r}
scores %>% 
  select(-sex)
```

## Excercise 11.11

```{r}
scores %>% 
  select(-sex, -reading_score)
```

## Excercise 11.12

```{r}

scores %>% 
  select(sex, everything())
```

## Excercise 11.13

```{r}
scores %>% 
  filter(sex == "male" & school == "south")
```

## Excercise 11.14

```{r}

scores %>%
    filter(math_score > mean(math_score))
```

## Excercise 11.19

```{r}
scores %>% 
  group_by(teacher) %>% 
  filter(max(math_score) == 5)
```

## Excercise 11.21

```{r}
scores %>% 
  mutate(
      math_score =  math_score * 10, 
      reading_score = reading_score * 10
  )
```